# Generated by Django 3.2.9 on 2021-11-04 18:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import hashid_field.field
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('data', models.JSONField(editable=False, null=True)),
                ('name', models.CharField(blank=True, default='(Unknown)', editable=False, max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('state', django_fsm.FSMIntegerField(choices=[(0, 'New')], default=0)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('ssn', models.CharField(max_length=100)),
                ('is_diploma', models.BooleanField(default=False)),
                ('is_certificate', models.BooleanField(default=False)),
                ('is_criminal', models.BooleanField(default=False)),
                ('criminal_notes', models.TextField(blank=True)),
                ('is_offender', models.BooleanField(default=False)),
                ('is_wasd', models.BooleanField(default=False)),
                ('wasd_notes', models.TextField(blank=True)),
                ('schools', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('notes', models.TextField(blank=True, default='', max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
