# Generated by Django 3.2.9 on 2021-11-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_account_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ssn',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
