# Generated by Django 3.1.7 on 2021-02-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_assignment_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.IntegerField(blank=True, choices=[(100, 'Elementary'), (200, 'Middle'), (300, 'High')], null=True),
        ),
    ]
